#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (52.72%)
# Total Accepted:    135.9K
# Total Submissions: 257.8K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(t) - len(s) != 1:
            return ""
        #统计各个字符的个数list，默认都是小写
        char_list = [0]*26
        for index in range(len(s)):
            char_list[ord(s[index])-ord('a')] -= 1
            char_list[ord(t[index])-ord('a')] += 1
        char_list[ord(t[-1])-ord('a')] += 1

        for index in range(len(char_list)):
            if char_list[index] == 1:
                return chr(ord('a')+index)
        return ""
        

